# -*- coding: utf-8 -*-
"""Append Extend pop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jh93u7oQPm3Lw8KtepOjT6mY79kWuYY7
"""

##append() Function Questions

##1- Write a program to append the number 100 to the given list.
##Input: [10, 20, 30, 40]

number = [10, 20, 30, 40]

new = number.append(100)
print(number)

##3 Write a program to append a list [5, 6, 7] as a single element in the given list.
##Input: [1, 2, 3, 4]

element = [1, 2, 3, 4]

new = element.append([5,6,7])
print(element)

##extend() Function Questions
#4 Write a program to extend the given list by adding another list [50, 60, 70].
#Input: [10, 20, 30, 40]

list = [10, 20, 30, 40]

new = list.extend([50,60,70])

print(list)

#5 Write a program to extend a list of numbers [7, 8, 9] with another list [10, 11, 12].
#Input: [7, 8, 9]

list =[7, 8, 9]

list.extend([10,11,12])
print(list)

#6 Write a program to extend a list of strings ["cat", "dog"] with another list ["lion", "tiger"].
#Input: ["cat", "dog"]
input = ["cat", "dog"]

input.extend(["lion","tiger"])
print(input)

##pop() Function Questions
##7 Write a program to remove the last element from the given list using the pop function.
##Input: [10, 20, 30, 40]
element = [10, 20, 30, 40]
element.pop()

#8 Write a program to remove the third element from the given list using the pop function.
#Input: [1, 2, 3, 4, 5]

input = [1, 2, 3, 4, 5]
input.pop(2)
print(input)

#9 Write a program to remove the first element from the given list using the pop function.
#Input: [100, 200, 300, 400]
input = [100, 200, 300, 400]

input.pop(0)
print(input)

#remove() Function Questions
#10 Write a program to remove the element 20 from the given list.
#Input: [10, 20, 30, 40, 50]

numbers =  [10, 20, 30, 40, 50]
numbers.remove(20)

print(numbers)

#11 Write a program to remove the first occurrence of "apple" from the given list.
#Input: ["banana", "apple", "cherry", "apple"]

Input=["banana", "apple", "cherry", "apple"]

Input.remove('apple')

print(Input)

#12 Write a program to remove the number 5 from the given list if it exists.
#Input: [1, 2, 3, 4, 5, 6]
numbers =  [1, 2, 3, 4, 5, 6]

numbers.remove(5)

print(numbers)

#index() Function Questions
#13 Write a program to find the index of the element 50 in the given list.
#Input: [10, 20, 30, 40, 50, 60]

Input=[10, 20, 30, 40, 50, 60]

new = Input.index(50)

print(new)

#14 Write a program to find the index of "cherry" in the given list.
#Input: ["apple", "banana", "cherry", "date"]

Input= ["apple", "banana", "cherry", "date"]

new = Input.index('cherry')

print(new)

#15 Write a program to find the index of the number 100 in the given list. If not found, print "Not found".
#Input: [10, 20, 30, 40]

Input= [10, 20, 30, 40]

if 100 in Input:
  print(number.index(100))
else:
  print("Not found")

#count() Function Questions
#16 Write a program to count the occurrences of 5 in the given list.
#Input: [1, 5, 2, 5, 3, 5, 4]

Input= [1, 5, 2, 5, 3, 5, 4]

new = Input.count(5)

print(new)

#17 Write a program to count how many times "apple" appears in the given list.
#Input: ["apple", "banana", "apple", "cherry", "apple"]

Input=["apple", "banana", "apple", "cherry", "apple"]

new=Input.count("apple")

print(new)

#18 Write a program to count the occurrences of 100 in the given list.
#Input: [10, 20, 30, 40, 50]

Input= [10, 20, 30, 40, 50]

new = Input.count(100)

print(new)

#min() and max() Function Questions
#19 Write a program to find the minimum value in the given list.
#Input: [45, 12, 78, 34, 23]

numbers = [45, 12, 78, 34, 23]

minimum_value = min(numbers)

print(minimum_value)

#20 Write a program to find the maximum value in the given list.
#Input: [99, 55, 73, 21, 64]

numbers = [45, 12, 78, 34, 23]

minimum_value = min(numbers)

print(minimum_value)