# -*- coding: utf-8 -*-
"""List Slicing Que.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1D88kodVNa0rnzA9kf4-2Z-x21fSWO3
"""

##List Indexing, Slicing, and Nested Slicing Questions
##1- Write a program to access the third element from the given list.
##Input: [10, 20, 30, 40, 50]

number =[10, 20, 30, 40, 50]

third_Element = number[2]

print(third_Element)

##2 Write a program to access the last element from the given list using negative indexing.
##Input: ['apple', 'banana', 'cherry', 'date']

fruits = ['apple', 'banana', 'cherry', 'date']

last_element = fruits[-1]
print(last_element)

##3 Write a program to change the second element to 100 in the given list.
##Input: [5, 10, 15, 20, 25]

Num = [5, 10, 15, 20, 25]

Num[1] = 100

print(Num)

##4 Write a program to access the first element using negative indexing.
##Input: [7, 14, 21, 28, 35]

Number = [7, 14, 21, 28, 35]

negetive = Number[-5]

print(negetive)

##5 Write a program to access the second last element from the given list.
##Input: [1, 2, 3, 4, 5, 6]

num2 = [1, 2, 3, 4, 5, 6]

second_last = num2[-2]

print(second_last)

##Slicing Questions
##6 Write a program to extract the first three elements from the given list.
##Input: [100, 200, 300, 400, 500, 600]

numbers = [100, 200, 300, 400, 500, 600]

three = numbers[:3]

print(three)

##7 Write a program to extract all elements except the first two from the given list.
##Input: [2, 4, 6, 8, 10, 12]

numbers2 = [2, 4, 6, 8, 10, 12]

result = numbers2[2:]

print(result)

##8 Write a program to extract every alternate element from the given list.
##Input: [5, 10, 15, 20, 25, 30, 35]

numbers11 = [5, 10, 15, 20, 25, 30, 35]

alternate = numbers11 [::2]

print(alternate)

##9 Write a program to reverse the given list using slicing.
##Input: [1, 3, 5, 7, 9]

input = [1, 3, 5, 7, 9]

reversed_slicing = input [::-1]

print(reversed_slicing)

##10 Write a program to extract elements from index 2 to 5 from the given list.
##Input: [11, 22, 33, 44, 55, 66, 77]

numbers = [11, 22, 33, 44, 55, 66, 77]

new = numbers[2:6]

print(new)

##Nested Slicing Questions
##11 Write a program to access the second element from the first nested list.
##Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

new = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

nested_slicing = new[0][1]

print(nested_slicing)

##12 Write a program to extract the last element from the last nested list.
##Input: [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
##Output: i

nested = [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]

last = nested[-1][-1]

print(last)

##13 Write a program to extract the second and third lists from a given nested list.
##Input: [[10, 20], [30, 40], [50, 60], [70, 80]]

nested_list = [[10, 20], [30, 40], [50, 60], [70, 80]]

lst = nested_list [1:3]

print(lst)

##14 Write a program to extract the second element from all nested lists.
##Input: [[1, 9], [2, 8], [3, 7], [4, 6]]
lst = [[1, 9], [2, 8], [3, 7], [4, 6]]

result = [ sublist[1] for sublist in lst]
print(result)

##15 Write a program to reverse all sublists in a nested list.
##Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

sub = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

reverse = [sublist[::-1] for sublist in sub]

print(reverse)

