# -*- coding: utf-8 -*-
"""tic tak toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1vjTbBZPcLbponiRoawOe_IZDksC4k_
"""

board = [' ' for _ in range(9)]

def print_board():
    print()
    print(f"{board[0]} | {board[1]} | {board[2]}")
    print("--+---+--")
    print(f"{board[3]} | {board[4]} | {board[5]}")
    print("--+---+--")
    print(f"{board[6]} | {board[7]} | {board[8]}")
    print()

def check_winner(player):

    win_combinations = [
        [0,1,2], [3,4,5], [6,7,8],
        [0,3,6], [1,4,7], [2,5,8],
        [0,4,8], [2,4,6]
    ]
    for combo in win_combinations:
        if all(board[i] == player for i in combo):
            return True
    return False

def is_draw():
    return ' ' not in board

def play_game():
    current_player = 'X'
    print("Welcome to Tic Tac Toe!")
    print_board()

    while True:
        try:
            move = int(input(f"Player {current_player}, choose a position (1-9): ")) - 1


            if board[move] != ' ':
                print("Cell already occupied. Try again.")
                continue

            board[move] = current_player
            print_board()


            if check_winner(current_player):
                print(f" Player {current_player} wins!")
                break
            elif is_draw():
                print(" draw!")
                break


            current_player = 'O' if current_player == 'X' else 'X'

        except (ValueError, IndexError):
            print("Invalid input! Please enter between 1 and 9.")

    again = input("play again? (y/n): ").lower()
    if again == 'y':
        for i in range(9):
            board[i] = ' '
        play_game()
    else:
        print("Thanks for playing...!")
play_game()

